//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductMarket.Domain.Resources.Errors {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProductMarket.Application.Resources.Errors.ErrorMessage", typeof(ErrorMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidClientRequrest.
        /// </summary>
        public static string InvalidClientRequrest {
            get {
                return ResourceManager.GetString("InvalidClientRequrest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InvalidToken.
        /// </summary>
        public static string InvalidToken {
            get {
                return ResourceManager.GetString("InvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordIsWrong.
        /// </summary>
        public static string PasswordIsWrong {
            get {
                return ResourceManager.GetString("PasswordIsWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PasswordsDontMatch.
        /// </summary>
        public static string PasswordsDontMatch {
            get {
                return ResourceManager.GetString("PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductAlreadyExists.
        /// </summary>
        public static string ProductAlreadyExists {
            get {
                return ResourceManager.GetString("ProductAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductDeleteError.
        /// </summary>
        public static string ProductDeleteError {
            get {
                return ResourceManager.GetString("ProductDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductErrorCreate.
        /// </summary>
        public static string ProductErrorCreate {
            get {
                return ResourceManager.GetString("ProductErrorCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductIsNotFound.
        /// </summary>
        public static string ProductIsNotFound {
            get {
                return ResourceManager.GetString("ProductIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductNotDetected.
        /// </summary>
        public static string ProductNotDetected {
            get {
                return ResourceManager.GetString("ProductNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductUnexpectedError.
        /// </summary>
        public static string ProductUnexpectedError {
            get {
                return ResourceManager.GetString("ProductUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProductUpdateError.
        /// </summary>
        public static string ProductUpdateError {
            get {
                return ResourceManager.GetString("ProductUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RemoveCartProductError.
        /// </summary>
        public static string RemoveCartProductError {
            get {
                return ResourceManager.GetString("RemoveCartProductError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleAlreadyExists.
        /// </summary>
        public static string RoleAlreadyExists {
            get {
                return ResourceManager.GetString("RoleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleHasAlreadyBeenAdded.
        /// </summary>
        public static string RoleHasAlreadyBeenAdded {
            get {
                return ResourceManager.GetString("RoleHasAlreadyBeenAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RoleNotFound.
        /// </summary>
        public static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnexpectedCartError.
        /// </summary>
        public static string UnexpectedCartError {
            get {
                return ResourceManager.GetString("UnexpectedCartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserAlreadyExists.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserNotFound.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserRegistrationUnexpectedError.
        /// </summary>
        public static string UserRegistrationUnexpectedError {
            get {
                return ResourceManager.GetString("UserRegistrationUnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserTokenCreationError.
        /// </summary>
        public static string UserTokenCreationError {
            get {
                return ResourceManager.GetString("UserTokenCreationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserTokenUpdateError.
        /// </summary>
        public static string UserTokenUpdateError {
            get {
                return ResourceManager.GetString("UserTokenUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to СartNotFoundError.
        /// </summary>
        public static string СartNotFoundError {
            get {
                return ResourceManager.GetString("СartNotFoundError", resourceCulture);
            }
        }
    }
}
